# Generated by Django 5.1.5 on 2025-01-17 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                ("studentId", models.AutoField(primary_key=True, serialize=False)),
                ("studentName", models.CharField(max_length=100)),
                ("collegeId", models.CharField(max_length=100)),
                ("place", models.CharField(max_length=100)),
                ("department", models.CharField(max_length=100)),
                ("studentClass", models.CharField(max_length=50)),
                ("year_of_admission", models.PositiveIntegerField()),
            ],
            options={
                "ordering": ["studentName"],
            },
        ),
        migrations.CreateModel(
            name="StudentAttendance",
            fields=[
                ("attendanceId", models.AutoField(primary_key=True, serialize=False)),
                ("studentName", models.CharField(max_length=100)),
                ("date", models.DateField()),
                ("time", models.TimeField()),
                ("studentClass", models.CharField(max_length=50)),
                (
                    "studentId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendances",
                        to="app.student",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-time"],
            },
        ),
    ]
