# Generated by Django 3.2.25 on 2025-01-18 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentattendance',
            name='period',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
