# Generated by Django 3.2.25 on 2025-01-18 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_student_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='imagePath',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
