# Generated by Django 5.1.5 on 2025-01-19 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_student_imagepath"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="status",
            field=models.IntegerField(default="0"),
        ),
    ]
