# Generated by Django 5.1.5 on 2025-01-19 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_student_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="collegeId",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
