# Generated by Django 5.1.5 on 2025-03-08 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_alter_student_collegeid"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="password",
            field=models.CharField(default=12345, max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="student",
            name="status",
            field=models.IntegerField(default=0),
        ),
    ]
