# Generated by Django 5.1.5 on 2025-03-08 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_student_password_alter_student_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "teacherId",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=100)),
                ("role", models.CharField(max_length=50)),
                ("department", models.CharField(max_length=100)),
                ("password", models.CharField(max_length=128)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("status", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
