# Generated by Django 5.1.5 on 2025-03-09 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_teacher"),
    ]

    operations = [
        migrations.CreateModel(
            name="LeaveRequest",
            fields=[
                ("requestId", models.AutoField(primary_key=True, serialize=False)),
                (
                    "requestType",
                    models.CharField(
                        choices=[
                            ("LEAVE", "Leave"),
                            ("ATTENDANCE_REVIEW", "Attendance Review"),
                        ],
                        max_length=20,
                    ),
                ),
                ("date", models.DateField()),
                ("reason", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Approved", "Approved"),
                            ("Rejected", "Rejected"),
                        ],
                        default="Pending",
                        max_length=50,
                    ),
                ),
                ("submittedDate", models.DateField(auto_now_add=True)),
                (
                    "studentId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_requests",
                        to="app.student",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                ("taskId", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                ("dueDate", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[("Pending", "Pending"), ("Completed", "Completed")],
                        default="Pending",
                        max_length=50,
                    ),
                ),
                ("assignedDate", models.DateField(auto_now_add=True)),
                (
                    "studentId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="app.student",
                    ),
                ),
            ],
        ),
    ]
