# Generated by Django 5.1.5 on 2025-03-09 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_leaverequest_task"),
    ]

    operations = [
        migrations.AddField(
            model_name="leaverequest",
            name="cause",
            field=models.TextField(blank=True, null=True),
        ),
    ]
